# Generated by Django 3.1.5 on 2021-01-31 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='anunciante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demanda.anunciante', verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.TextField(blank=True, verbose_name='Complemento'),
        ),
    ]
