# Generated by Django 3.1.5 on 2021-02-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0002_auto_20210131_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoDeEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('complemento', models.TextField(blank=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'endereco',
                'verbose_name_plural': 'enderecos',
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('info_contato', models.JSONField(verbose_name='Informações de Contato')),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('FI', 'Finalizado')], default='AB', max_length=2, verbose_name='Status de Finalização')),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demanda.anunciante')),
                ('endereco_de_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demanda.enderecodeentrega')),
            ],
        ),
    ]
